{% set name = "ConfigUpdater" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 430d3da24b7905a780cbd170765c09f16a74bb175d07e6a7eff2d621914bbc91

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - importlib-metadata

test:
  imports:
    - configupdater
  requires:
    - pip
    - pytest
    - pytest-cov
  source_files:
    - tests
  commands:
    - pytest
    - pip check

about:
  home: https://github.com/pyscaffold/configupdater
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Parser like ConfigParser but for updating configuration files
  description: |
    The sole purpose of ConfigUpdater is to easily update an INI config file
    with no changes to the original file except the intended ones. This means
    comments, the ordering of sections and key/value-pairs as wells as their
    cases are kept as in the original file. Thus ConfigUpdater provides
    complementary functionality to Python's ConfigParser which is primarily
    meant for reading config files and writing *new* ones.
  doc_url: https://configupdater.readthedocs.io/
  dev_url: https://github.com/pyscaffold/configupdater

extra:
  recipe-maintainers:
    - maresb
    - FlorianWilhelm
    - abravalheri
